### ISSUE TITLE
Can't compile - Error with TTY_LDISC_MAGIC

### ISSUE THREAD

**Issue by A13X15** [Greenzie/emuccan-b202#3]
When running `make`, I get the following error:

` /home/user/emuccan-b202/driver/main.c:117:4: error: ‘struct tty_ldisc_ops’ has no member named ‘magic’ `
` 117 |   .magic  = TTY_LDISC_MAGIC, `
` /home/user/emuccan-b202/driver/main.c:117:13: error: ‘TTY_LDISC_MAGIC’ undeclared here (not in a function); did you mean ‘TTY_LDISC_HALTED’? `
`117 |   .magic  = TTY_LDISC_MAGIC, 'TTY_LDISC_HALTED'`
`make[3]: *** [scripts/Makefile.build:281: /home/user/emuccan-b202/driver/main.o] Error 1 `...

My output for `uname -a` is:
`Linux pc-name 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

I have `linux-headers-generic` and `build-essential` installed. Is there anything else to care about?

**Comment by A13X15** [comment]
Follow-up: Will close the issue, found the problem.

Does not work with my kernel (5.13); older kernels (5.4, 5.11) work just fine, have not tried more kernels.
